### PR TITLE
Fix/various

### LINKED ISSUE #118: Mobile Version: Exit Tribute Page - awkward horizontal movement of page and image off-centre
This is similar to issue #115 

First arriving on the page, everything is zoomed in and you can't move the slider without moving the page:

When zoomed out, everything is off-centre and looks awkward:
image

### PR DESCRIPTION
**Pull request by MerlinEgalite**
Fix #118 , #117 , #115

### CODE REVIEW

**Review by mendesfabio — APPROVED** [review]
LGTM!

**Comment by laurenluz** [comment]
These pages are all still opening up zoomed in on the mobile version. And when I zoom our for hatchers and for exit tribute pages, it's still off-center

**Comment by MerlinEgalite** [comment]
weird... did you check here: https://commons-stack-game-dev.netlify.app/ ?
this is where you can see the changes

**Comment by laurenluz** [comment]
On it right now... The Hatchers page is still an issue (zoomed in/off centre) but the graph and the exit tribute page are good :)

**Pull request merged**
